name: education_app
description: Tobeto - Flutter 1A - Pair Project
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  flutter_bloc: ^8.1.4
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0

  webview_flutter: ^4.5.0
  appinio_video_player: ^1.3.0
  url_launcher: ^6.0.10

  auto_size_text: ^3.0.0
  image_picker: ^1.0.7
  file_picker: ^6.1.1
  firebase_storage: ^11.6.5
  equatable: ^2.0.5
  firebase_app_check: ^0.2.1+13
  rive: ^0.12.4
  font_awesome_flutter: ^10.7.0
  uuid: ^4.3.3
  flutter_local_notifications: ^16.3.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

    - assets/video/

    - assets/icons/


  fonts:
      - family: Tinos
        fonts:
          - asset: assets/fonts/Tinos-Regular.ttf
          - asset: assets/fonts/Tinos-Italic.ttf
          - asset: assets/fonts/Tinos-Bold.ttf
          - asset: assets/fonts/Tinos-BoldItalic.ttf

      - family: Poppins
        fonts:
          - asset: assets/fonts/Poppins-Regular.ttf