// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:education_app/constants/strings/FirebaseOptionsStrings.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          FirebaseOptionsStrings.windowsUnsupportedError,
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          FirebaseOptionsStrings.linuxUnsupportedError,
        );
      default:
        throw UnsupportedError(
          FirebaseOptionsStrings.defaultUnsupportedError,
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: FirebaseOptionsStrings.webApiKey,
    appId: FirebaseOptionsStrings.webAppId,
    messagingSenderId: FirebaseOptionsStrings.webMessagingSenderId,
    projectId: FirebaseOptionsStrings.webProjectId,
    authDomain: FirebaseOptionsStrings.webAuthDomain,
    storageBucket: FirebaseOptionsStrings.webStorageBucket,
    measurementId: FirebaseOptionsStrings.webMeasurementId,
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: FirebaseOptionsStrings.androidApiKey,
    appId: FirebaseOptionsStrings.androidAppId,
    messagingSenderId: FirebaseOptionsStrings.androidMessagingSenderId,
    projectId: FirebaseOptionsStrings.androidProjectId,
    storageBucket: FirebaseOptionsStrings.androidStorageBucket,
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: FirebaseOptionsStrings.iosApiKey,
    appId: FirebaseOptionsStrings.iosAppId,
    messagingSenderId: FirebaseOptionsStrings.iosMessagingSenderId,
    projectId: FirebaseOptionsStrings.iosProjectId,
    storageBucket: FirebaseOptionsStrings.iosStorageBucket,
    iosBundleId: FirebaseOptionsStrings.iosBundleId,
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: FirebaseOptionsStrings.macosApiKey,
    appId: FirebaseOptionsStrings.macosAppId,
    messagingSenderId: FirebaseOptionsStrings.macosMessagingSenderId,
    projectId: FirebaseOptionsStrings.macosProjectId,
    storageBucket: FirebaseOptionsStrings.macosStorageBucket,
    iosBundleId: FirebaseOptionsStrings.macosIosBundleId,
  );
}
