// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjxDW_45avDXhuH_b0MYeDCrhMdSJ4uJQ',
    appId: '1:1092978669938:web:58107e7f4ee09b352d05eb',
    messagingSenderId: '1092978669938',
    projectId: 'educationappdb',
    authDomain: 'educationappdb.firebaseapp.com',
    storageBucket: 'educationappdb.appspot.com',
    measurementId: 'G-1S4X303MRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_3FCJxh-xofRYjM2AE7DRTxAOqLj3JKs',
    appId: '1:1092978669938:android:68b17683b97b24952d05eb',
    messagingSenderId: '1092978669938',
    projectId: 'educationappdb',
    storageBucket: 'educationappdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk3GoUvFAXW_u1C243Q_0Jmb4VgOkWJN0',
    appId: '1:1092978669938:ios:60154672abb9c34b2d05eb',
    messagingSenderId: '1092978669938',
    projectId: 'educationappdb',
    storageBucket: 'educationappdb.appspot.com',
    iosBundleId: 'com.pair6.educationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk3GoUvFAXW_u1C243Q_0Jmb4VgOkWJN0',
    appId: '1:1092978669938:ios:2022cccc2c9a5d4b2d05eb',
    messagingSenderId: '1092978669938',
    projectId: 'educationappdb',
    storageBucket: 'educationappdb.appspot.com',
    iosBundleId: 'com.pair6.educationApp.RunnerTests',
  );
}
